# Generated by Django 6.1.1 on 2026-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='inspections/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('compliant', 'Compliant'), ('violation', 'Violation'), ('high_risk', 'High Risk')], default='pending', max_length=20)),
                ('compliance_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
